### ISSUE TITLE
Troubleshooting Error C1083 in Project "ArchLord"

### ISSUE THREAD

**Issue by Baloralys** [osiy1996/archlord#4]
Severity Code Description Project File Line Suppression State Details
Error C1083 Cannot open file (source): "..........\ArchLord\third-party\parson\parson.c": No such file or directory editor F:\ArchLord\third-party\parson\parson.c 1

**Comment by osiy1996** [comment]
https://github.com/osiy1996/archlord/commit/1deccbe62aaa0fb161ced95de088767659bb35f3
